// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

#if NET
using CoreWCF;
using CoreWCF.Channels;
using CoreWCF.Description;
using CoreWCF.Security;
#else
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.ServiceModel.Security;
#endif
using System;
using System.Security.Cryptography.X509Certificates;

namespace WcfService
{
    // Hosts IWcfService over NetTcp + TransportWithMessageCredential + certificate client
    // credentials with a deliberately short SessionKeyRenewalInterval so an SCT renewal exchange
    // is forced during a normal length test run. Used by the regression test for dotnet/wcf#5883
    // where the client's Renew message used to fail with an XmlException or a server rejection.
    [TestServiceDefinition(Schema = ServiceSchema.NETTCP, BasePath = "TcpSctRenewal.svc")]
    internal class TcpTransportSecurityMessageCredentialsCertRenewTestServiceHost : TestServiceHostBase<IWcfService>
    {
        protected override string Address { get { return "tcp-sct-renewal"; } }

        protected override Binding GetBinding()
        {
            NetTcpBinding binding = new NetTcpBinding(SecurityMode.TransportWithMessageCredential);
            binding.Security.Message.ClientCredentialType = MessageCredentialType.Certificate;

            BindingElementCollection elements = binding.CreateBindingElements();
            TransportSecurityBindingElement transportSecurity = elements.Find<TransportSecurityBindingElement>();
            if (transportSecurity != null)
            {
                transportSecurity.LocalServiceSettings.SessionKeyRenewalInterval = TimeSpan.FromSeconds(10);
                transportSecurity.LocalServiceSettings.SessionKeyRolloverInterval = TimeSpan.FromSeconds(3);
            }

            return new CustomBinding(elements);
        }

        protected override void ApplyConfiguration()
        {
            base.ApplyConfiguration();
            this.Credentials.ClientCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.Custom;
            this.Credentials.ClientCertificate.Authentication.CustomCertificateValidator = new MyX509CertificateValidator("DO_NOT_TRUST_WcfBridgeRootCA");

            X509Certificate2 cert = TestHost.CertificateFromFriendlyName(StoreName.My, StoreLocation.LocalMachine, "WCF Bridge - Machine certificate generated by the CertificateManager");
            this.Credentials.ServiceCertificate.Certificate = cert;
        }

        public TcpTransportSecurityMessageCredentialsCertRenewTestServiceHost(params Uri[] baseAddresses)
            : base(typeof(WcfService), baseAddresses)
        {
        }
    }
}
