// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

#if NET
using CoreWCF;
using CoreWCF.Channels;
using CoreWCF.Security;
#else
using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Security;
#endif
using System.Security.Cryptography.X509Certificates;

namespace WcfService
{
    [TestServiceDefinition(Schema = ServiceSchema.NETTCP, BasePath = "TcpTransSecMessCredsWindows.svc")]
    internal class TcpTransportSecurityMessageCredentialsWindowsTestServiceHost : TestServiceHostBase<IWcfService>
    {
        protected override IList<Binding> GetBindings()
        {
            return new List<Binding>
            {
                GetNetTcpBinding(),
                GetCustomBindingNoSecureConversation()
            };
        }

        private Binding GetNetTcpBinding()
        {
            NetTcpBinding binding = new NetTcpBinding(SecurityMode.TransportWithMessageCredential);
            binding.Security.Message.ClientCredentialType = MessageCredentialType.Windows;
            binding.Name = "tcp-message-credentials-windows";
            return binding;
        }

        private Binding GetCustomBindingNoSecureConversation()
        {
            // NetTcpBinding doesn't expose EstablishSecurityContext for TransportWithMessageCredential,
            // so use CustomBinding to create SSPI over transport without SecureConversation wrapper
            var sspiSecurity = SecurityBindingElement.CreateSspiNegotiationOverTransportBindingElement(true);
            sspiSecurity.IncludeTimestamp = true;
            sspiSecurity.LocalClientSettings.ReconnectTransportOnFailure = false;
            sspiSecurity.MessageSecurityVersion = MessageSecurityVersion.WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11;

            CustomBinding binding = new CustomBinding(
                sspiSecurity,
                new BinaryMessageEncodingBindingElement(),
                new SslStreamSecurityBindingElement(),
                new TcpTransportBindingElement());
            binding.Name = "tcp-message-credentials-windows-nosc";
            return binding;
        }

        protected override void ApplyConfiguration()
        {
            base.ApplyConfiguration();

            X509Certificate2 cert = TestHost.CertificateFromFriendlyName(StoreName.My, StoreLocation.LocalMachine, "WCF Bridge - Machine certificate generated by the CertificateManager");
            this.Credentials.ServiceCertificate.Certificate = cert;
        }

        public TcpTransportSecurityMessageCredentialsWindowsTestServiceHost(params Uri[] baseAddresses)
            : base(typeof(WcfService), baseAddresses)
        {
        }
    }
}
