//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageContract_NS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexCompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class ComplexCompositeType : object
    {
        
        private bool BoolValueField;
        
        private byte[] ByteArrayValueField;
        
        private char[] CharArrayValueField;
        
        private char CharValueField;
        
        private System.DateTime DateTimeValueField;
        
        private System.DayOfWeek DayOfWeekValueField;
        
        private double DoubleValueField;
        
        private float FloatValueField;
        
        private System.Guid GuidValueField;
        
        private int IntValueField;
        
        private long LongValueField;
        
        private string LongerStringValueField;
        
        private sbyte SbyteValueField;
        
        private short ShortValueField;
        
        private string StringValueField;
        
        private System.TimeSpan TimeSpanValueField;
        
        private uint UintValueField;
        
        private ulong UlongValueField;
        
        private ushort UshortValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ByteArrayValue
        {
            get
            {
                return this.ByteArrayValueField;
            }
            set
            {
                this.ByteArrayValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] CharArrayValue
        {
            get
            {
                return this.CharArrayValueField;
            }
            set
            {
                this.CharArrayValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CharValue
        {
            get
            {
                return this.CharValueField;
            }
            set
            {
                this.CharValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeValue
        {
            get
            {
                return this.DateTimeValueField;
            }
            set
            {
                this.DateTimeValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek DayOfWeekValue
        {
            get
            {
                return this.DayOfWeekValueField;
            }
            set
            {
                this.DayOfWeekValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DoubleValue
        {
            get
            {
                return this.DoubleValueField;
            }
            set
            {
                this.DoubleValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FloatValue
        {
            get
            {
                return this.FloatValueField;
            }
            set
            {
                this.FloatValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GuidValue
        {
            get
            {
                return this.GuidValueField;
            }
            set
            {
                this.GuidValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntValue
        {
            get
            {
                return this.IntValueField;
            }
            set
            {
                this.IntValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LongValue
        {
            get
            {
                return this.LongValueField;
            }
            set
            {
                this.LongValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongerStringValue
        {
            get
            {
                return this.LongerStringValueField;
            }
            set
            {
                this.LongerStringValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte SbyteValue
        {
            get
            {
                return this.SbyteValueField;
            }
            set
            {
                this.SbyteValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ShortValue
        {
            get
            {
                return this.ShortValueField;
            }
            set
            {
                this.ShortValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeSpanValue
        {
            get
            {
                return this.TimeSpanValueField;
            }
            set
            {
                this.TimeSpanValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint UintValue
        {
            get
            {
                return this.UintValueField;
            }
            set
            {
                this.UintValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong UlongValue
        {
            get
            {
                return this.UlongValueField;
            }
            set
            {
                this.UlongValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort UshortValue
        {
            get
            {
                return this.UshortValueField;
            }
            set
            {
                this.UshortValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class FaultDetail : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfstring", Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class ResultOfstring : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private System.Net.HttpStatusCode HttpStatusCodeField;
        
        private string ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Net.HttpStatusCode HttpStatusCode
        {
            get
            {
                return this.HttpStatusCodeField;
            }
            set
            {
                this.HttpStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfUserGamePlay", Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class ResultOfArrayOfUserGamePlay : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private System.Net.HttpStatusCode HttpStatusCodeField;
        
        private MessageContract_NS.UserGamePlay[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Net.HttpStatusCode HttpStatusCode
        {
            get
            {
                return this.HttpStatusCodeField;
            }
            set
            {
                this.HttpStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MessageContract_NS.UserGamePlay[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGamePlay", Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class UserGamePlay : object
    {
        
        private string GameKeyField;
        
        private string KeyField;
        
        private string TimeStampField;
        
        private string UserIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameKey
        {
            get
            {
                return this.GameKeyField;
            }
            set
            {
                this.GameKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestHttpRequestMessageProperty", Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class TestHttpRequestMessageProperty : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> HeadersField;
        
        private string MethodField;
        
        private string QueryStringField;
        
        private bool SuppressEntityBodyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Headers
        {
            get
            {
                return this.HeadersField;
            }
            set
            {
                this.HeadersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method
        {
            get
            {
                return this.MethodField;
            }
            set
            {
                this.MethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString
        {
            get
            {
                return this.QueryStringField;
            }
            set
            {
                this.QueryStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressEntityBody
        {
            get
            {
                return this.SuppressEntityBodyField;
            }
            set
            {
                this.SuppressEntityBodyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageContract_NS.IWcfProjectNService")]
    public interface IWcfProjectNService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoWithTimeout", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoWithTimeoutResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.EchoWithTimeoutResponse> EchoWithTimeoutAsync(MessageContract_NS.EchoWithTimeoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageRequestReply", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageRequestReplyResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> MessageRequestReplyAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/Echo", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.EchoResponse> EchoAsync(MessageContract_NS.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoComplex", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoComplexResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.EchoComplexResponse> EchoComplexAsync(MessageContract_NS.EchoComplexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/TestFault", ReplyAction="http://tempuri.org/IWcfProjectNService/TestFaultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MessageContract_NS.FaultDetail), Action="http://tempuri.org/IWcfProjectNService/TestFaultFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
        System.Threading.Tasks.Task<MessageContract_NS.TestFaultResponse> TestFaultAsync(MessageContract_NS.TestFaultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/ThrowInvalidOperationException", ReplyAction="http://tempuri.org/IWcfProjectNService/ThrowInvalidOperationExceptionResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.ThrowInvalidOperationExceptionResponse> ThrowInvalidOperationExceptionAsync(MessageContract_NS.ThrowInvalidOperationExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWcfProjectNService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(MessageContract_NS.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/ValidateMessagePropertyHeaders", ReplyAction="http://tempuri.org/IWcfProjectNService/ValidateMessagePropertyHeadersResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.ValidateMessagePropertyHeadersResponse> ValidateMessagePropertyHeadersAsync(MessageContract_NS.ValidateMessagePropertyHeadersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/UserGetAuthToken", ReplyAction="http://tempuri.org/IWcfProjectNService/UserGetAuthTokenResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.UserGetAuthTokenResponse> UserGetAuthTokenAsync(MessageContract_NS.UserGetAuthTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/UserGamePlayGetList", ReplyAction="http://tempuri.org/IWcfProjectNService/UserGamePlayGetListResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.UserGamePlayGetListResponse> UserGamePlayGetListAsync(MessageContract_NS.UserGamePlayGetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageContractRequestReply", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.ReplyBankingData> MessageContractRequestReplyAsync(MessageContract_NS.RequestBankingData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyNotWrapped", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyNotWrappedRespo" +
            "nse")]
        System.Threading.Tasks.Task<MessageContract_NS.ReplyBankingDataNotWrapped> MessageContractRequestReplyNotWrappedAsync(MessageContract_NS.RequestBankingData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoHttpMessageProperty", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoHttpRequestMessagePropertyResponse")]
        System.Threading.Tasks.Task<MessageContract_NS.EchoHttpRequestMessagePropertyResponse> EchoHttpRequestMessagePropertyAsync(MessageContract_NS.EchoHttpRequestMessagePropertyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoWithTimeout", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoWithTimeoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string message;
        
        public EchoWithTimeoutRequest()
        {
        }
        
        public EchoWithTimeoutRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoWithTimeoutResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoWithTimeoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EchoWithTimeoutResult;
        
        public EchoWithTimeoutResponse()
        {
        }
        
        public EchoWithTimeoutResponse(string EchoWithTimeoutResult)
        {
            this.EchoWithTimeoutResult = EchoWithTimeoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Echo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string message;
        
        public EchoRequest()
        {
        }
        
        public EchoRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EchoResult;
        
        public EchoResponse()
        {
        }
        
        public EchoResponse(string EchoResult)
        {
            this.EchoResult = EchoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoComplex", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoComplexRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.ComplexCompositeType message;
        
        public EchoComplexRequest()
        {
        }
        
        public EchoComplexRequest(MessageContract_NS.ComplexCompositeType message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoComplexResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoComplexResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.ComplexCompositeType EchoComplexResult;
        
        public EchoComplexResponse()
        {
        }
        
        public EchoComplexResponse(MessageContract_NS.ComplexCompositeType EchoComplexResult)
        {
            this.EchoComplexResult = EchoComplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestFault", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestFaultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string faultMsg;
        
        public TestFaultRequest()
        {
        }
        
        public TestFaultRequest(string faultMsg)
        {
            this.faultMsg = faultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestFaultResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestFaultResponse
    {
        
        public TestFaultResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThrowInvalidOperationException", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThrowInvalidOperationExceptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string message;
        
        public ThrowInvalidOperationExceptionRequest()
        {
        }
        
        public ThrowInvalidOperationExceptionRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThrowInvalidOperationExceptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThrowInvalidOperationExceptionResponse
    {
        
        public ThrowInvalidOperationExceptionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(MessageContract_NS.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(MessageContract_NS.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMessagePropertyHeaders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateMessagePropertyHeadersRequest
    {
        
        public ValidateMessagePropertyHeadersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMessagePropertyHeadersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateMessagePropertyHeadersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> ValidateMessagePropertyHeadersResult;
        
        public ValidateMessagePropertyHeadersResponse()
        {
        }
        
        public ValidateMessagePropertyHeadersResponse(System.Collections.Generic.Dictionary<string, string> ValidateMessagePropertyHeadersResult)
        {
            this.ValidateMessagePropertyHeadersResult = ValidateMessagePropertyHeadersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGetAuthToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGetAuthTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string liveId;
        
        public UserGetAuthTokenRequest()
        {
        }
        
        public UserGetAuthTokenRequest(string liveId)
        {
            this.liveId = liveId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGetAuthTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGetAuthTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.ResultOfstring UserGetAuthTokenResult;
        
        public UserGetAuthTokenResponse()
        {
        }
        
        public UserGetAuthTokenResponse(MessageContract_NS.ResultOfstring UserGetAuthTokenResult)
        {
            this.UserGetAuthTokenResult = UserGetAuthTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGamePlayGetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGamePlayGetListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string gameKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string keys;
        
        public UserGamePlayGetListRequest()
        {
        }
        
        public UserGamePlayGetListRequest(string gameKey, string keys)
        {
            this.gameKey = gameKey;
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGamePlayGetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGamePlayGetListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.ResultOfArrayOfUserGamePlay UserGamePlayGetListResult;
        
        public UserGamePlayGetListResponse()
        {
        }
        
        public UserGamePlayGetListResponse(MessageContract_NS.ResultOfArrayOfUserGamePlay UserGamePlayGetListResult)
        {
            this.UserGamePlayGetListResult = UserGamePlayGetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomWrapperName", WrapperNamespace="http://mycustomwrappernamespace.com", IsWrapped=true)]
    public partial class RequestBankingData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CustomNamespace", Order=2)]
        public string Customer_Name;
        
        public RequestBankingData()
        {
        }
        
        public RequestBankingData(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomWrapperName", WrapperNamespace="http://mycustomwrappernamespace.com", IsWrapped=true)]
    public partial class ReplyBankingData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CustomNamespace", Order=2)]
        public string Customer_Name;
        
        public ReplyBankingData()
        {
        }
        
        public ReplyBankingData(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplyBankingDataNotWrapped
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mycustomcustomernamespace.com", Order=2)]
        public string Customer_Name;
        
        public ReplyBankingDataNotWrapped()
        {
        }
        
        public ReplyBankingDataNotWrapped(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoHttpRequestMessageProperty", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoHttpRequestMessagePropertyRequest
    {
        
        public EchoHttpRequestMessagePropertyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoHttpRequestMessagePropertyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoHttpRequestMessagePropertyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageContract_NS.TestHttpRequestMessageProperty EchoHttpRequestMessagePropertyResult;
        
        public EchoHttpRequestMessagePropertyResponse()
        {
        }
        
        public EchoHttpRequestMessagePropertyResponse(MessageContract_NS.TestHttpRequestMessageProperty EchoHttpRequestMessagePropertyResult)
        {
            this.EchoHttpRequestMessagePropertyResult = EchoHttpRequestMessagePropertyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public interface IWcfProjectNServiceChannel : MessageContract_NS.IWcfProjectNService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public partial class WcfProjectNServiceClient : System.ServiceModel.ClientBase<MessageContract_NS.IWcfProjectNService>, MessageContract_NS.IWcfProjectNService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), WcfProjectNServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.EchoWithTimeoutResponse> EchoWithTimeoutAsync(MessageContract_NS.EchoWithTimeoutRequest request)
        {
            return base.Channel.EchoWithTimeoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> MessageRequestReplyAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.MessageRequestReplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.EchoResponse> EchoAsync(MessageContract_NS.EchoRequest request)
        {
            return base.Channel.EchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.EchoComplexResponse> EchoComplexAsync(MessageContract_NS.EchoComplexRequest request)
        {
            return base.Channel.EchoComplexAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.TestFaultResponse> TestFaultAsync(MessageContract_NS.TestFaultRequest request)
        {
            return base.Channel.TestFaultAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.ThrowInvalidOperationExceptionResponse> ThrowInvalidOperationExceptionAsync(MessageContract_NS.ThrowInvalidOperationExceptionRequest request)
        {
            return base.Channel.ThrowInvalidOperationExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(MessageContract_NS.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.ValidateMessagePropertyHeadersResponse> ValidateMessagePropertyHeadersAsync(MessageContract_NS.ValidateMessagePropertyHeadersRequest request)
        {
            return base.Channel.ValidateMessagePropertyHeadersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.UserGetAuthTokenResponse> UserGetAuthTokenAsync(MessageContract_NS.UserGetAuthTokenRequest request)
        {
            return base.Channel.UserGetAuthTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.UserGamePlayGetListResponse> UserGamePlayGetListAsync(MessageContract_NS.UserGamePlayGetListRequest request)
        {
            return base.Channel.UserGamePlayGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.ReplyBankingData> MessageContractRequestReplyAsync(MessageContract_NS.RequestBankingData request)
        {
            return base.Channel.MessageContractRequestReplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.ReplyBankingDataNotWrapped> MessageContractRequestReplyNotWrappedAsync(MessageContract_NS.RequestBankingData request)
        {
            return base.Channel.MessageContractRequestReplyNotWrappedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageContract_NS.EchoHttpRequestMessagePropertyResponse> EchoHttpRequestMessagePropertyAsync(MessageContract_NS.EchoHttpRequestMessagePropertyRequest request)
        {
            return base.Channel.EchoHttpRequestMessagePropertyAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.defaultEndpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.defaultBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpsEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap12Endpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpbinaryEndpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap12Endpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding1))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.defaultEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.defaultBasic))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/Basic");
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/basicHttp");
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpsEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/basicHttps");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpsoap11");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpsoap12");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpbinaryEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpbinary");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/httpssoap11");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/httpssoap12");
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProj" +
                        "ectNService.svc/tcpdefault");
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding1))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProj" +
                        "ectNService.svc/tcpnosecurity");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            defaultEndpoint,
            
            defaultBasic,
            
            basicHttpEndpoint,
            
            basicHttpsEndpoint,
            
            httpsoap11Endpoint,
            
            httpsoap12Endpoint,
            
            httpbinaryEndpoint,
            
            httpssoap11Endpoint,
            
            httpssoap12Endpoint,
            
            nettcpdefaultBinding,
            
            nettcpdefaultBinding1,
        }
    }
}