//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlSerializer_NS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class FaultDetail
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class ComplexCompositeType
    {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private byte[] byteArrayValueField;
        
        private int[] charArrayValueField;
        
        private int charValueField;
        
        private bool charValueFieldSpecified;
        
        private System.DateTime dateTimeValueField;
        
        private bool dateTimeValueFieldSpecified;
        
        private DayOfWeek dayOfWeekValueField;
        
        private bool dayOfWeekValueFieldSpecified;
        
        private double doubleValueField;
        
        private bool doubleValueFieldSpecified;
        
        private float floatValueField;
        
        private bool floatValueFieldSpecified;
        
        private string guidValueField;
        
        private int intValueField;
        
        private bool intValueFieldSpecified;
        
        private long longValueField;
        
        private bool longValueFieldSpecified;
        
        private string longerStringValueField;
        
        private sbyte sbyteValueField;
        
        private bool sbyteValueFieldSpecified;
        
        private short shortValueField;
        
        private bool shortValueFieldSpecified;
        
        private string stringValueField;
        
        private string timeSpanValueField;
        
        private uint uintValueField;
        
        private bool uintValueFieldSpecified;
        
        private ulong ulongValueField;
        
        private bool ulongValueFieldSpecified;
        
        private ushort ushortValueField;
        
        private bool ushortValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue
        {
            get
            {
                return this.boolValueField;
            }
            set
            {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified
        {
            get
            {
                return this.boolValueFieldSpecified;
            }
            set
            {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[] ByteArrayValue
        {
            get
            {
                return this.byteArrayValueField;
            }
            set
            {
                this.byteArrayValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("char", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] CharArrayValue
        {
            get
            {
                return this.charArrayValueField;
            }
            set
            {
                this.charArrayValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CharValue
        {
            get
            {
                return this.charValueField;
            }
            set
            {
                this.charValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CharValueSpecified
        {
            get
            {
                return this.charValueFieldSpecified;
            }
            set
            {
                this.charValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateTimeValue
        {
            get
            {
                return this.dateTimeValueField;
            }
            set
            {
                this.dateTimeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateTimeValueSpecified
        {
            get
            {
                return this.dateTimeValueFieldSpecified;
            }
            set
            {
                this.dateTimeValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DayOfWeek DayOfWeekValue
        {
            get
            {
                return this.dayOfWeekValueField;
            }
            set
            {
                this.dayOfWeekValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DayOfWeekValueSpecified
        {
            get
            {
                return this.dayOfWeekValueFieldSpecified;
            }
            set
            {
                this.dayOfWeekValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double DoubleValue
        {
            get
            {
                return this.doubleValueField;
            }
            set
            {
                this.doubleValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoubleValueSpecified
        {
            get
            {
                return this.doubleValueFieldSpecified;
            }
            set
            {
                this.doubleValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float FloatValue
        {
            get
            {
                return this.floatValueField;
            }
            set
            {
                this.floatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FloatValueSpecified
        {
            get
            {
                return this.floatValueFieldSpecified;
            }
            set
            {
                this.floatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GuidValue
        {
            get
            {
                return this.guidValueField;
            }
            set
            {
                this.guidValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IntValue
        {
            get
            {
                return this.intValueField;
            }
            set
            {
                this.intValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntValueSpecified
        {
            get
            {
                return this.intValueFieldSpecified;
            }
            set
            {
                this.intValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long LongValue
        {
            get
            {
                return this.longValueField;
            }
            set
            {
                this.longValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongValueSpecified
        {
            get
            {
                return this.longValueFieldSpecified;
            }
            set
            {
                this.longValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string LongerStringValue
        {
            get
            {
                return this.longerStringValueField;
            }
            set
            {
                this.longerStringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public sbyte SbyteValue
        {
            get
            {
                return this.sbyteValueField;
            }
            set
            {
                this.sbyteValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SbyteValueSpecified
        {
            get
            {
                return this.sbyteValueFieldSpecified;
            }
            set
            {
                this.sbyteValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public short ShortValue
        {
            get
            {
                return this.shortValueField;
            }
            set
            {
                this.shortValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShortValueSpecified
        {
            get
            {
                return this.shortValueFieldSpecified;
            }
            set
            {
                this.shortValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=15)]
        public string TimeSpanValue
        {
            get
            {
                return this.timeSpanValueField;
            }
            set
            {
                this.timeSpanValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public uint UintValue
        {
            get
            {
                return this.uintValueField;
            }
            set
            {
                this.uintValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UintValueSpecified
        {
            get
            {
                return this.uintValueFieldSpecified;
            }
            set
            {
                this.uintValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ulong UlongValue
        {
            get
            {
                return this.ulongValueField;
            }
            set
            {
                this.ulongValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UlongValueSpecified
        {
            get
            {
                return this.ulongValueFieldSpecified;
            }
            set
            {
                this.ulongValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public ushort UshortValue
        {
            get
            {
                return this.ushortValueField;
            }
            set
            {
                this.ushortValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UshortValueSpecified
        {
            get
            {
                return this.ushortValueFieldSpecified;
            }
            set
            {
                this.ushortValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public enum DayOfWeek
    {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmlSerializer_NS.IWcfProjectNService")]
    public interface IWcfProjectNService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoWithTimeout", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoWithTimeoutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoWithTimeoutResponse> EchoWithTimeoutAsync(XmlSerializer_NS.EchoWithTimeoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageRequestReply", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageRequestReplyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> MessageRequestReplyAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/Echo", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoResponse> EchoAsync(XmlSerializer_NS.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoComplex", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoComplexResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoComplexResponse> EchoComplexAsync(XmlSerializer_NS.EchoComplexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/TestFault", ReplyAction="http://tempuri.org/IWcfProjectNService/TestFaultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(XmlSerializer_NS.FaultDetail), Action="http://tempuri.org/IWcfProjectNService/TestFaultFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.TestFaultResponse> TestFaultAsync(XmlSerializer_NS.TestFaultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/ThrowInvalidOperationException", ReplyAction="http://tempuri.org/IWcfProjectNService/ThrowInvalidOperationExceptionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ThrowInvalidOperationExceptionResponse> ThrowInvalidOperationExceptionAsync(XmlSerializer_NS.ThrowInvalidOperationExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWcfProjectNService/GetDataUsingDataContractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(XmlSerializer_NS.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/ValidateMessagePropertyHeaders", ReplyAction="http://tempuri.org/IWcfProjectNService/ValidateMessagePropertyHeadersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ValidateMessagePropertyHeadersResponse> ValidateMessagePropertyHeadersAsync(XmlSerializer_NS.ValidateMessagePropertyHeadersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/UserGetAuthToken", ReplyAction="http://tempuri.org/IWcfProjectNService/UserGetAuthTokenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.UserGetAuthTokenResponse> UserGetAuthTokenAsync(XmlSerializer_NS.UserGetAuthTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/UserGamePlayGetList", ReplyAction="http://tempuri.org/IWcfProjectNService/UserGamePlayGetListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.UserGamePlayGetListResponse> UserGamePlayGetListAsync(XmlSerializer_NS.UserGamePlayGetListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageContractRequestReply", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ReplyBankingData> MessageContractRequestReplyAsync(XmlSerializer_NS.RequestBankingData request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyNotWrapped", ReplyAction="http://tempuri.org/IWcfProjectNService/MessageContractRequestReplyNotWrappedRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ReplyBankingDataNotWrapped> MessageContractRequestReplyNotWrappedAsync(XmlSerializer_NS.RequestBankingData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfProjectNService/EchoHttpMessageProperty", ReplyAction="http://tempuri.org/IWcfProjectNService/EchoHttpRequestMessagePropertyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoHttpRequestMessagePropertyResponse> EchoHttpRequestMessagePropertyAsync(XmlSerializer_NS.EchoHttpRequestMessagePropertyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoWithTimeout", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoWithTimeoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message;
        
        public EchoWithTimeoutRequest()
        {
        }
        
        public EchoWithTimeoutRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoWithTimeoutResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoWithTimeoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EchoWithTimeoutResult;
        
        public EchoWithTimeoutResponse()
        {
        }
        
        public EchoWithTimeoutResponse(string EchoWithTimeoutResult)
        {
            this.EchoWithTimeoutResult = EchoWithTimeoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Echo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message;
        
        public EchoRequest()
        {
        }
        
        public EchoRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EchoResult;
        
        public EchoResponse()
        {
        }
        
        public EchoResponse(string EchoResult)
        {
            this.EchoResult = EchoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoComplex", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoComplexRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.ComplexCompositeType message;
        
        public EchoComplexRequest()
        {
        }
        
        public EchoComplexRequest(XmlSerializer_NS.ComplexCompositeType message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoComplexResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoComplexResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.ComplexCompositeType EchoComplexResult;
        
        public EchoComplexResponse()
        {
        }
        
        public EchoComplexResponse(XmlSerializer_NS.ComplexCompositeType EchoComplexResult)
        {
            this.EchoComplexResult = EchoComplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestFault", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestFaultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string faultMsg;
        
        public TestFaultRequest()
        {
        }
        
        public TestFaultRequest(string faultMsg)
        {
            this.faultMsg = faultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestFaultResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestFaultResponse
    {
        
        public TestFaultResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThrowInvalidOperationException", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThrowInvalidOperationExceptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message;
        
        public ThrowInvalidOperationExceptionRequest()
        {
        }
        
        public ThrowInvalidOperationExceptionRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThrowInvalidOperationExceptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThrowInvalidOperationExceptionResponse
    {
        
        public ThrowInvalidOperationExceptionResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class CompositeType
    {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue
        {
            get
            {
                return this.boolValueField;
            }
            set
            {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified
        {
            get
            {
                return this.boolValueFieldSpecified;
            }
            set
            {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(XmlSerializer_NS.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(XmlSerializer_NS.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMessagePropertyHeaders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateMessagePropertyHeadersRequest
    {
        
        public ValidateMessagePropertyHeadersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMessagePropertyHeadersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateMessagePropertyHeadersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public XmlSerializer_NS.ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] ValidateMessagePropertyHeadersResult;
        
        public ValidateMessagePropertyHeadersResponse()
        {
        }
        
        public ValidateMessagePropertyHeadersResponse(XmlSerializer_NS.ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] ValidateMessagePropertyHeadersResult)
        {
            this.ValidateMessagePropertyHeadersResult = ValidateMessagePropertyHeadersResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class ResultOfstring
    {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        private HttpStatusCode httpStatusCodeField;
        
        private bool httpStatusCodeFieldSpecified;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HttpStatusCode HttpStatusCode
        {
            get
            {
                return this.httpStatusCodeField;
            }
            set
            {
                this.httpStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HttpStatusCodeSpecified
        {
            get
            {
                return this.httpStatusCodeFieldSpecified;
            }
            set
            {
                this.httpStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Net")]
    public enum HttpStatusCode
    {
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        SwitchingProtocols,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NonAuthoritativeInformation,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        ResetContent,
        
        /// <remarks/>
        PartialContent,
        
        /// <remarks/>
        MultipleChoices,
        
        /// <remarks/>
        Ambiguous,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Moved,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        Redirect,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        RedirectMethod,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        UseProxy,
        
        /// <remarks/>
        Unused,
        
        /// <remarks/>
        TemporaryRedirect,
        
        /// <remarks/>
        RedirectKeepVerb,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        PaymentRequired,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        NotAcceptable,
        
        /// <remarks/>
        ProxyAuthenticationRequired,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        Gone,
        
        /// <remarks/>
        LengthRequired,
        
        /// <remarks/>
        PreconditionFailed,
        
        /// <remarks/>
        RequestEntityTooLarge,
        
        /// <remarks/>
        RequestUriTooLong,
        
        /// <remarks/>
        UnsupportedMediaType,
        
        /// <remarks/>
        RequestedRangeNotSatisfiable,
        
        /// <remarks/>
        ExpectationFailed,
        
        /// <remarks/>
        UpgradeRequired,
        
        /// <remarks/>
        InternalServerError,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        BadGateway,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        GatewayTimeout,
        
        /// <remarks/>
        HttpVersionNotSupported,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGetAuthToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGetAuthTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string liveId;
        
        public UserGetAuthTokenRequest()
        {
        }
        
        public UserGetAuthTokenRequest(string liveId)
        {
            this.liveId = liveId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGetAuthTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGetAuthTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.ResultOfstring UserGetAuthTokenResult;
        
        public UserGetAuthTokenResponse()
        {
        }
        
        public UserGetAuthTokenResponse(XmlSerializer_NS.ResultOfstring UserGetAuthTokenResult)
        {
            this.UserGetAuthTokenResult = UserGetAuthTokenResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wcf.projectn.com/wcfnamespace")]
    public partial class ResultOfArrayOfUserGamePlay
    {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        private HttpStatusCode httpStatusCodeField;
        
        private bool httpStatusCodeFieldSpecified;
        
        private UserGamePlay[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HttpStatusCode HttpStatusCode
        {
            get
            {
                return this.httpStatusCodeField;
            }
            set
            {
                this.httpStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HttpStatusCodeSpecified
        {
            get
            {
                return this.httpStatusCodeFieldSpecified;
            }
            set
            {
                this.httpStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
        public UserGamePlay[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class UserGamePlay
    {
        
        private string gameKeyField;
        
        private string keyField;
        
        private string timeStampField;
        
        private string userIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GameKey
        {
            get
            {
                return this.gameKeyField;
            }
            set
            {
                this.gameKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGamePlayGetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGamePlayGetListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gameKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string keys;
        
        public UserGamePlayGetListRequest()
        {
        }
        
        public UserGamePlayGetListRequest(string gameKey, string keys)
        {
            this.gameKey = gameKey;
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGamePlayGetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserGamePlayGetListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.ResultOfArrayOfUserGamePlay UserGamePlayGetListResult;
        
        public UserGamePlayGetListResponse()
        {
        }
        
        public UserGamePlayGetListResponse(XmlSerializer_NS.ResultOfArrayOfUserGamePlay UserGamePlayGetListResult)
        {
            this.UserGamePlayGetListResult = UserGamePlayGetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomWrapperName", WrapperNamespace="http://mycustomwrappernamespace.com", IsWrapped=true)]
    public partial class RequestBankingData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/")]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CustomNamespace", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="CustomNamespace", IsNullable=true)]
        public string Customer_Name;
        
        public RequestBankingData()
        {
        }
        
        public RequestBankingData(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomWrapperName", WrapperNamespace="http://mycustomwrappernamespace.com", IsWrapped=true)]
    public partial class ReplyBankingData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/")]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CustomNamespace", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="CustomNamespace", IsNullable=true)]
        public string Customer_Name;
        
        public ReplyBankingData()
        {
        }
        
        public ReplyBankingData(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplyBankingDataNotWrapped
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime Date_of_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Transaction_Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mycustomcustomernamespace.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Customer_Name;
        
        public ReplyBankingDataNotWrapped()
        {
        }
        
        public ReplyBankingDataNotWrapped(System.DateTime Date_of_Request, int Transaction_Amount, string Customer_Name)
        {
            this.Date_of_Request = Date_of_Request;
            this.Transaction_Amount = Transaction_Amount;
            this.Customer_Name = Customer_Name;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfProjectNService")]
    public partial class TestHttpRequestMessageProperty
    {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] headersField;
        
        private string methodField;
        
        private string queryStringField;
        
        private bool suppressEntityBodyField;
        
        private bool suppressEntityBodyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] Headers
        {
            get
            {
                return this.headersField;
            }
            set
            {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string QueryString
        {
            get
            {
                return this.queryStringField;
            }
            set
            {
                this.queryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SuppressEntityBody
        {
            get
            {
                return this.suppressEntityBodyField;
            }
            set
            {
                this.suppressEntityBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressEntityBodySpecified
        {
            get
            {
                return this.suppressEntityBodyFieldSpecified;
            }
            set
            {
                this.suppressEntityBodyFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoHttpRequestMessageProperty", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoHttpRequestMessagePropertyRequest
    {
        
        public EchoHttpRequestMessagePropertyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoHttpRequestMessagePropertyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EchoHttpRequestMessagePropertyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XmlSerializer_NS.TestHttpRequestMessageProperty EchoHttpRequestMessagePropertyResult;
        
        public EchoHttpRequestMessagePropertyResponse()
        {
        }
        
        public EchoHttpRequestMessagePropertyResponse(XmlSerializer_NS.TestHttpRequestMessageProperty EchoHttpRequestMessagePropertyResult)
        {
            this.EchoHttpRequestMessagePropertyResult = EchoHttpRequestMessagePropertyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public interface IWcfProjectNServiceChannel : XmlSerializer_NS.IWcfProjectNService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public partial class WcfProjectNServiceClient : System.ServiceModel.ClientBase<XmlSerializer_NS.IWcfProjectNService>, XmlSerializer_NS.IWcfProjectNService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), WcfProjectNServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WcfProjectNServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WcfProjectNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoWithTimeoutResponse> XmlSerializer_NS.IWcfProjectNService.EchoWithTimeoutAsync(XmlSerializer_NS.EchoWithTimeoutRequest request)
        {
            return base.Channel.EchoWithTimeoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.EchoWithTimeoutResponse> EchoWithTimeoutAsync(string message)
        {
            XmlSerializer_NS.EchoWithTimeoutRequest inValue = new XmlSerializer_NS.EchoWithTimeoutRequest();
            inValue.message = message;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).EchoWithTimeoutAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> MessageRequestReplyAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.MessageRequestReplyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoResponse> XmlSerializer_NS.IWcfProjectNService.EchoAsync(XmlSerializer_NS.EchoRequest request)
        {
            return base.Channel.EchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.EchoResponse> EchoAsync(string message)
        {
            XmlSerializer_NS.EchoRequest inValue = new XmlSerializer_NS.EchoRequest();
            inValue.message = message;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).EchoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoComplexResponse> XmlSerializer_NS.IWcfProjectNService.EchoComplexAsync(XmlSerializer_NS.EchoComplexRequest request)
        {
            return base.Channel.EchoComplexAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.EchoComplexResponse> EchoComplexAsync(XmlSerializer_NS.ComplexCompositeType message)
        {
            XmlSerializer_NS.EchoComplexRequest inValue = new XmlSerializer_NS.EchoComplexRequest();
            inValue.message = message;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).EchoComplexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.TestFaultResponse> XmlSerializer_NS.IWcfProjectNService.TestFaultAsync(XmlSerializer_NS.TestFaultRequest request)
        {
            return base.Channel.TestFaultAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.TestFaultResponse> TestFaultAsync(string faultMsg)
        {
            XmlSerializer_NS.TestFaultRequest inValue = new XmlSerializer_NS.TestFaultRequest();
            inValue.faultMsg = faultMsg;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).TestFaultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ThrowInvalidOperationExceptionResponse> XmlSerializer_NS.IWcfProjectNService.ThrowInvalidOperationExceptionAsync(XmlSerializer_NS.ThrowInvalidOperationExceptionRequest request)
        {
            return base.Channel.ThrowInvalidOperationExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.ThrowInvalidOperationExceptionResponse> ThrowInvalidOperationExceptionAsync(string message)
        {
            XmlSerializer_NS.ThrowInvalidOperationExceptionRequest inValue = new XmlSerializer_NS.ThrowInvalidOperationExceptionRequest();
            inValue.message = message;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).ThrowInvalidOperationExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.GetDataUsingDataContractResponse> XmlSerializer_NS.IWcfProjectNService.GetDataUsingDataContractAsync(XmlSerializer_NS.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(XmlSerializer_NS.CompositeType composite)
        {
            XmlSerializer_NS.GetDataUsingDataContractRequest inValue = new XmlSerializer_NS.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).GetDataUsingDataContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.ValidateMessagePropertyHeadersResponse> XmlSerializer_NS.IWcfProjectNService.ValidateMessagePropertyHeadersAsync(XmlSerializer_NS.ValidateMessagePropertyHeadersRequest request)
        {
            return base.Channel.ValidateMessagePropertyHeadersAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.ValidateMessagePropertyHeadersResponse> ValidateMessagePropertyHeadersAsync()
        {
            XmlSerializer_NS.ValidateMessagePropertyHeadersRequest inValue = new XmlSerializer_NS.ValidateMessagePropertyHeadersRequest();
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).ValidateMessagePropertyHeadersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.UserGetAuthTokenResponse> XmlSerializer_NS.IWcfProjectNService.UserGetAuthTokenAsync(XmlSerializer_NS.UserGetAuthTokenRequest request)
        {
            return base.Channel.UserGetAuthTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.UserGetAuthTokenResponse> UserGetAuthTokenAsync(string liveId)
        {
            XmlSerializer_NS.UserGetAuthTokenRequest inValue = new XmlSerializer_NS.UserGetAuthTokenRequest();
            inValue.liveId = liveId;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).UserGetAuthTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.UserGamePlayGetListResponse> XmlSerializer_NS.IWcfProjectNService.UserGamePlayGetListAsync(XmlSerializer_NS.UserGamePlayGetListRequest request)
        {
            return base.Channel.UserGamePlayGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.UserGamePlayGetListResponse> UserGamePlayGetListAsync(string gameKey, string keys)
        {
            XmlSerializer_NS.UserGamePlayGetListRequest inValue = new XmlSerializer_NS.UserGamePlayGetListRequest();
            inValue.gameKey = gameKey;
            inValue.keys = keys;
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).UserGamePlayGetListAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.ReplyBankingData> MessageContractRequestReplyAsync(XmlSerializer_NS.RequestBankingData request)
        {
            return base.Channel.MessageContractRequestReplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.ReplyBankingDataNotWrapped> MessageContractRequestReplyNotWrappedAsync(XmlSerializer_NS.RequestBankingData request)
        {
            return base.Channel.MessageContractRequestReplyNotWrappedAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlSerializer_NS.EchoHttpRequestMessagePropertyResponse> XmlSerializer_NS.IWcfProjectNService.EchoHttpRequestMessagePropertyAsync(XmlSerializer_NS.EchoHttpRequestMessagePropertyRequest request)
        {
            return base.Channel.EchoHttpRequestMessagePropertyAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlSerializer_NS.EchoHttpRequestMessagePropertyResponse> EchoHttpRequestMessagePropertyAsync()
        {
            XmlSerializer_NS.EchoHttpRequestMessagePropertyRequest inValue = new XmlSerializer_NS.EchoHttpRequestMessagePropertyRequest();
            return ((XmlSerializer_NS.IWcfProjectNService)(this)).EchoHttpRequestMessagePropertyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.defaultEndpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.defaultBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpsEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap12Endpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpbinaryEndpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap12Endpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding1))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.defaultEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.defaultBasic))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/Basic");
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/basicHttp");
            }
            if ((endpointConfiguration == EndpointConfiguration.basicHttpsEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/basicHttps");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpsoap11");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpsoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpsoap12");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpbinaryEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProject" +
                        "NService.svc/httpbinary");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/httpssoap11");
            }
            if ((endpointConfiguration == EndpointConfiguration.httpssoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProjec" +
                        "tNService.svc/httpssoap12");
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProj" +
                        "ectNService.svc/tcpdefault");
            }
            if ((endpointConfiguration == EndpointConfiguration.nettcpdefaultBinding1))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://wcfprojectnserver.redmond.corp.microsoft.com/WcfProjectNService/WcfProj" +
                        "ectNService.svc/tcpnosecurity");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            defaultEndpoint,
            
            defaultBasic,
            
            basicHttpEndpoint,
            
            basicHttpsEndpoint,
            
            httpsoap11Endpoint,
            
            httpsoap12Endpoint,
            
            httpbinaryEndpoint,
            
            httpssoap11Endpoint,
            
            httpssoap12Endpoint,
            
            nettcpdefaultBinding,
            
            nettcpdefaultBinding1,
        }
    }
}