// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpMessageCredentialType))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpMessageSecurity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpsBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpSecurity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpSecurityMode))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpsSecurity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpsSecurityMode))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.HttpBindingBase))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.HttpClientCredentialType))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.HttpProxyCredentialType))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.HttpTransportSecurity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.MessageSecurityOverHttp))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.NetHttpBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.NetHttpMessageEncoding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.NetHttpsBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.NonDualMessageSecurityOverHttp))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.WS2007HttpBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.WSHttpBinding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.WSHttpBindingBase))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.WSHttpSecurity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.WSMessageEncoding))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpMessageHandlerFactory))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpRequestMessageExtensionMethods))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpRequestMessageProperty))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpResponseMessageProperty))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpsTransportBindingElement))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.HttpTransportBindingElement))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.IHttpCookieContainerManager))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.WebSocketTransportSettings))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.WebSocketTransportUsage))]
