<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="StreamedService" targetNamespace="http://tempuri.org/">
<wsp:Policy wsu:Id="NetNamedPipeBinding_IStreamedService_policy">
<wsp:ExactlyOne>
<wsp:All>
<msb:BinaryEncoding xmlns:msb="http://schemas.microsoft.com/ws/06/2004/mspolicy/netbinary1"/>
<msf:Streamed xmlns:msf="http://schemas.microsoft.com/ws/2006/05/framing/policy"/>
<wsaw:UsingAddressing/>
</wsp:All>
</wsp:ExactlyOne>
</wsp:Policy>
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/Message" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/Message">
<xs:simpleType name="StreamBody">
<xs:restriction base="xs:base64Binary"/>
</xs:simpleType>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
<xs:import namespace="http://schemas.microsoft.com/Message"/>
<xs:element name="UploadStream">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q1="http://schemas.microsoft.com/Message" name="data" type="q1:StreamBody"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="UploadStreamResponse">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="UploadStreamResult" type="xs:dateTime"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetDisconnectResult">
<xs:complexType>
<xs:sequence/>
</xs:complexType>
</xs:element>
<xs:element name="GetDisconnectResultResponse">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="GetDisconnectResultResult" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
<xs:element name="anyType" nillable="true" type="xs:anyType"/>
<xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
<xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
<xs:element name="boolean" nillable="true" type="xs:boolean"/>
<xs:element name="byte" nillable="true" type="xs:byte"/>
<xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
<xs:element name="decimal" nillable="true" type="xs:decimal"/>
<xs:element name="double" nillable="true" type="xs:double"/>
<xs:element name="float" nillable="true" type="xs:float"/>
<xs:element name="int" nillable="true" type="xs:int"/>
<xs:element name="long" nillable="true" type="xs:long"/>
<xs:element name="QName" nillable="true" type="xs:QName"/>
<xs:element name="short" nillable="true" type="xs:short"/>
<xs:element name="string" nillable="true" type="xs:string"/>
<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
<xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
<xs:element name="char" nillable="true" type="tns:char"/>
<xs:simpleType name="char">
<xs:restriction base="xs:int"/>
</xs:simpleType>
<xs:element name="duration" nillable="true" type="tns:duration"/>
<xs:simpleType name="duration">
<xs:restriction base="xs:duration">
<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
<xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
<xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
</xs:restriction>
</xs:simpleType>
<xs:element name="guid" nillable="true" type="tns:guid"/>
<xs:simpleType name="guid">
<xs:restriction base="xs:string">
<xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
</xs:restriction>
</xs:simpleType>
<xs:attribute name="FactoryType" type="xs:QName"/>
<xs:attribute name="Id" type="xs:ID"/>
<xs:attribute name="Ref" type="xs:IDREF"/>
</xs:schema>
</wsdl:types>
<wsdl:message name="IStreamedService_UploadStream_InputMessage">
<wsdl:part name="parameters" element="tns:UploadStream"/>
</wsdl:message>
<wsdl:message name="IStreamedService_UploadStream_OutputMessage">
<wsdl:part name="parameters" element="tns:UploadStreamResponse"/>
</wsdl:message>
<wsdl:message name="IStreamedService_GetDisconnectResult_InputMessage">
<wsdl:part name="parameters" element="tns:GetDisconnectResult"/>
</wsdl:message>
<wsdl:message name="IStreamedService_GetDisconnectResult_OutputMessage">
<wsdl:part name="parameters" element="tns:GetDisconnectResultResponse"/>
</wsdl:message>
<wsdl:portType name="IStreamedService">
<wsdl:operation name="UploadStream">
<wsdl:input wsaw:Action="http://tempuri.org/IStreamedService/UploadStream" message="tns:IStreamedService_UploadStream_InputMessage"/>
<wsdl:output wsaw:Action="http://tempuri.org/IStreamedService/UploadStreamResponse" message="tns:IStreamedService_UploadStream_OutputMessage"/>
</wsdl:operation>
<wsdl:operation name="GetDisconnectResult">
<wsdl:input wsaw:Action="http://tempuri.org/IStreamedService/GetDisconnectResult" message="tns:IStreamedService_GetDisconnectResult_InputMessage"/>
<wsdl:output wsaw:Action="http://tempuri.org/IStreamedService/GetDisconnectResultResponse" message="tns:IStreamedService_GetDisconnectResult_OutputMessage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="NetNamedPipeBinding_IStreamedService" type="tns:IStreamedService">
<wsp:PolicyReference URI="#NetNamedPipeBinding_IStreamedService_policy"/>
<soap12:binding transport="http://schemas.microsoft.com/soap/named-pipe"/>
<wsdl:operation name="UploadStream">
<soap12:operation soapAction="http://tempuri.org/IStreamedService/UploadStream" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="GetDisconnectResult">
<soap12:operation soapAction="http://tempuri.org/IStreamedService/GetDisconnectResult" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="StreamedService">
<wsdl:port name="NetNamedPipeBinding_IStreamedService" binding="tns:NetNamedPipeBinding_IStreamedService">
<soap12:address location="net.pipe://vcarwan01.redmond.corp.microsoft.com/IISHost/StreamedService.svc"/>
<wsa10:EndpointReference>
<wsa10:Address>net.pipe://localhost/IISHost/StreamedService.svc</wsa10:Address>
</wsa10:EndpointReference>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>