// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using WcfTestBridgeCommon;

namespace WcfService.CertificateResources
{
    internal class MachineCertificateResource : CertificateResource
    {
        public MachineCertificateResource() : base() { }

        public override ResourceResponse Get(ResourceRequestContext context)
        {
            string subject;
            ResourceResponse response = new ResourceResponse();

            // if no subject parameter provided, provide a list of certs already generated
            if (!context.Properties.TryGetValue(subjectResourceString, out subject) || string.IsNullOrWhiteSpace(subject))
            {
                string retVal = string.Empty;
                string[] subjects; 
                string[] thumbprints;

                lock (s_certificateResourceLock)
                {
                    int certNum = s_createdCerts.Count;
                    subjects = new string[certNum];
                    thumbprints = new string[certNum];

                    foreach (var keyVal in s_createdCerts)
                    {
                        --certNum;
                        subjects[certNum] = keyVal.Key;
                        thumbprints[certNum] = keyVal.Value.Thumbprint; 
                    }
                }

                response.Properties.Add(subjectssResourceString, string.Join(",", subjects));
                response.Properties.Add(thumbprintsResourceString, string.Join(",", thumbprints));
                return response; 
            }

            // Otherwise, check on the creation state
            X509Certificate2 certificate;
            bool certHasBeenCreated;

            lock (s_certificateResourceLock)
            {
                certHasBeenCreated = s_createdCerts.TryGetValue(subject, out certificate);
            }

            if (certHasBeenCreated)
            {
                response.Properties.Add(thumbprintResourceString, certificate.Thumbprint);
                response.Properties.Add(certificateResourceString, Convert.ToBase64String(certificate.RawData));
            }
            else
            {
                response.Properties.Add(thumbprintResourceString, string.Empty);
                response.Properties.Add(certificateResourceString, string.Empty);
            }
            return response;
        }

        // Requests a certificate to be generated by the Bridge
        // If the certificate requested is for the local machine, for example if 
        // server hostname is: foo.bar.com
        // local address is considered to be: 127.0.0.1, localhost, foo, foo.bar.com
        // Then we also install the certificate to the local machine, because it means we are about to run an HTTPS/SSL test against 
        // this machine. 
        // Otherwise, don't bother installing as the cert is for a remote machine. 
        public override ResourceResponse Put(ResourceRequestContext context)
        {
            X509Certificate2 certificate;

            string subject; 
            if (!context.Properties.TryGetValue(subjectResourceString, out subject) || string.IsNullOrWhiteSpace(subject))
            {
                throw new ArgumentException("When PUTting to this resource, specify an non-empty 'subject'", "context.Properties");
            }

            // There can be multiple subjects, separated by ,
            string[] subjects = subject.Split(',');

            bool isLocal = IsLocalMachineResource(subjects[0]);

            lock (s_certificateResourceLock)
            {
                if (!s_createdCerts.TryGetValue(subjects[0], out certificate))
                {
                    CertificateGenerator generator = CertificateResourceHelpers.GetCertificateGeneratorInstance(context.BridgeConfiguration);

                    if (isLocal)
                    {
                        // If we're PUTting a cert that refers to a hostname local to the bridge, 
                        // return the Local Machine cert that CertificateManager caches and add it to the collection
                        //
                        // If we are receiving a PUT to the same endpoint address as the bridge server, it means that 
                        // a test is going to be run on this box
                        //
                        // In keeping with the semantic of these classes, we must PUT before we can GET a cert
                        certificate = CertificateManager.CreateAndInstallLocalMachineCertificates(generator);
                        s_createdCerts.Add(subjects[0], certificate);

                    }
                    else
                    {
                        certificate = generator.CreateCertificate(subjects).Certificate;
                        s_createdCerts.Add(subjects[0], certificate);
                    }
                }
            }

            ResourceResponse response = new ResourceResponse();
            response.Properties.Add(thumbprintResourceString, certificate.Thumbprint);
            response.Properties.Add(isLocalResourceString, isLocal.ToString());

            return response;
        }
    }
}
