//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

namespace System.Web.Services {
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class ResWebServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResWebServices() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.ServiceModel.Svcutil.System.Web.Services.ResWebServices", typeof(ResWebServices).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Binding &apos;{0}&apos; from namespace &apos;{1}&apos;..
        /// </summary>
        internal static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The element attribute is not allowed on encoded message parts. The erroneous part is named &apos;{0}&apos; in message &apos;{1}&apos;..
        /// </summary>
        internal static string CanTSpecifyElementOnEncodedMessagePartsPart {
            get {
                return ResourceManager.GetString("CanTSpecifyElementOnEncodedMessagePartsPart", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to CODEGEN: {0}.
        /// </summary>
        internal static string CodegenWarningDetails {
            get {
                return ResourceManager.GetString("CodegenWarningDetails", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Service description with targetNamespace=&apos;{0}&apos;..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to {0} from service description with targetNamespace=&apos;{1}&apos;..
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to soapbind:fault &apos;{0}&apos; on operation &apos;{1}&apos; on portType &apos;{2}&apos; from namespace &apos;{3}&apos;. {4}.
        /// </summary>
        internal static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fault &apos;{0}&apos; on operation &apos;{1}&apos; on binding &apos;{2}&apos; from namespace &apos;{3}&apos;..
        /// </summary>
        internal static string FaultBinding {
            get {
                return ResourceManager.GetString("FaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} on operation &apos;{1}&apos; on portType &apos;{2}&apos; from namespace &apos;{3}&apos;. {4}.
        /// </summary>
        internal static string HeaderFault {
            get {
                return ResourceManager.GetString("HeaderFault", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Message &apos;{0}&apos; from service description with targetNamespace=&apos;{1}&apos;..
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Missing message part &apos;{0}&apos; for message &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string MissingMessagePartForMessageFromNamespace3 {
            get {
                return ResourceManager.GetString("MissingMessagePartForMessageFromNamespace3", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Only objects of type OperationInput or OperationOutput may be added..
        /// </summary>
        internal static string OnlyOperationInputOrOperationOutputTypes {
            get {
                return ResourceManager.GetString("OnlyOperationInputOrOperationOutputTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only XmlElements or types deriving from ServiceDescriptionFormatExtension may be added..
        /// </summary>
        internal static string OnlyXmlElementsOrTypesDerivingFromServiceDescriptionFormatExtension0 {
            get {
                return ResourceManager.GetString("OnlyXmlElementsOrTypesDerivingFromServiceDescriptionFormatExtension0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operation &apos;{0}&apos; on portType &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operation &apos;{0}&apos; on binding &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string OperationBinding {
            get {
                return ResourceManager.GetString("OperationBinding", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Part &apos;{0}&apos; of message &apos;{1}&apos; from service description with targetNamespace=&apos;{2}&apos;..
        /// </summary>
        internal static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Port &apos;{0}&apos; on service {1} from namespace=&apos;{2}&apos;..
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Protocol with name &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string ProtocolWithNameIsNotRecognized1 {
            get {
                return ResourceManager.GetString("ProtocolWithNameIsNotRecognized1", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Required XmlFormatExtension attribute is missing on class {0}..
        /// </summary>
        internal static string RequiredXmlFormatExtensionAttributeIsMissing1 {
            get {
                return ResourceManager.GetString("RequiredXmlFormatExtensionAttributeIsMissing1", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Schema with targetNamespace=&apos;{0}&apos; has invalid syntax. {1} Line {2}, position {3}..
        /// </summary>
        internal static string SchemaSyntaxErrorDetails {
            get {
                return ResourceManager.GetString("SchemaSyntaxErrorDetails", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Schema validation error: {0}.
        /// </summary>
        internal static string SchemaValidationError {
            get {
                return ResourceManager.GetString("SchemaValidationError", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The syntax of type {0} may not be extended..
        /// </summary>
        internal static string TheSyntaxOfTypeMayNotBeExtended1 {
            get {
                return ResourceManager.GetString("TheSyntaxOfTypeMayNotBeExtended1", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Error: {0} Line {1}, position {2}..
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Cannot find definition for {0}.  Service Description with namespace {1} is missing..
        /// </summary>
        internal static string WebDescriptionMissing {
            get {
                return ResourceManager.GetString("WebDescriptionMissing", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Element {0} named {1} from namespace {2} is missing..
        /// </summary>
        internal static string WebDescriptionMissingItem {
            get {
                return ResourceManager.GetString("WebDescriptionMissingItem", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to No more than one input and one output message may be specified..
        /// </summary>
        internal static string WebDescriptionTooManyMessages {
            get {
                return ResourceManager.GetString("WebDescriptionTooManyMessages", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to More than one binding named &apos;{0}&apos; was specified. Each binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateBinding {
            get {
                return ResourceManager.GetString("WebDuplicateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one fault binding named &apos;{0}&apos; was specified. Each fault binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateFaultBinding {
            get {
                return ResourceManager.GetString("WebDuplicateFaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one format extension named &apos;{0}&apos; was specified. Each format extension must have a unique name..
        /// </summary>
        internal static string WebDuplicateFormatExtension {
            get {
                return ResourceManager.GetString("WebDuplicateFormatExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one import named &apos;{0}&apos; was specified. Each import must have a unique name..
        /// </summary>
        internal static string WebDuplicateImport {
            get {
                return ResourceManager.GetString("WebDuplicateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one message named &apos;{0}&apos; was specified. Each message must have a unique name..
        /// </summary>
        internal static string WebDuplicateMessage {
            get {
                return ResourceManager.GetString("WebDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one message part named &apos;{0}&apos; was specified. Each message part must have a unique name..
        /// </summary>
        internal static string WebDuplicateMessagePart {
            get {
                return ResourceManager.GetString("WebDuplicateMessagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one operation named &apos;{0}&apos; was specified. Each operation must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperation {
            get {
                return ResourceManager.GetString("WebDuplicateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one operation binding named &apos;{0}&apos; was specified. Each operation binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationBinding {
            get {
                return ResourceManager.GetString("WebDuplicateOperationBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one operation fault named &apos;{0}&apos; was specified. Each operation fault must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationFault {
            get {
                return ResourceManager.GetString("WebDuplicateOperationFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one operation message named &apos;{0}&apos; was specified. Each operation message must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationMessage {
            get {
                return ResourceManager.GetString("WebDuplicateOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one port named &apos;{0}&apos; was specified. Each port must have a unique name..
        /// </summary>
        internal static string WebDuplicatePort {
            get {
                return ResourceManager.GetString("WebDuplicatePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one port type named &apos;{0}&apos; was specified. Each port type must have a unique name..
        /// </summary>
        internal static string WebDuplicatePortType {
            get {
                return ResourceManager.GetString("WebDuplicatePortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one service named &apos;{0}&apos; was specified. Each service must have a unique name..
        /// </summary>
        internal static string WebDuplicateService {
            get {
                return ResourceManager.GetString("WebDuplicateService", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to More than one {0} named &apos;{1}&apos; was specified. Each {0} must have a unique name..
        /// </summary>
        internal static string WebDuplicateUnknownElement {
            get {
                return ResourceManager.GetString("WebDuplicateUnknownElement", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The value for &apos;{0}&apos; cannot be negative..
        /// </summary>
        internal static string WebNegativeValue {
            get {
                return ResourceManager.GetString("WebNegativeValue", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Warning: {0}.
        /// </summary>
        internal static string WsdlInstanceValidation {
            get {
                return ResourceManager.GetString("WsdlInstanceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Warning: {0} Line {1}, position {2}..
        /// </summary>
        internal static string WsdlInstanceValidationDetails {
            get {
                return ResourceManager.GetString("WsdlInstanceValidationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to en.
        /// </summary>
        internal static string XmlLang {
            get {
                return ResourceManager.GetString("XmlLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Schema with targetNamespace=&apos;{0}&apos; has invalid syntax. {1}.
        /// </summary>
        internal static string XmlSchema {
            get {
                return ResourceManager.GetString("XmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attribute reference &apos;{0}&apos; declared in schema type &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string XmlSchemaAttributeReference {
            get {
                return ResourceManager.GetString("XmlSchemaAttributeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Check content definition of schema type &apos;{0}&apos; from namespace &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string XmlSchemaContentDef {
            get {
                return ResourceManager.GetString("XmlSchemaContentDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Element reference &apos;{0}&apos; declared in schema type &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string XmlSchemaElementReference {
            get {
                return ResourceManager.GetString("XmlSchemaElementReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Schema item &apos;{1}&apos; from namespace &apos;{0}&apos;. {2}.
        /// </summary>
        internal static string XmlSchemaItem {
            get {
                return ResourceManager.GetString("XmlSchemaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Schema item &apos;{1}&apos; named &apos;{2}&apos; from namespace &apos;{0}&apos; is invalid. {3}.
        /// </summary>
        internal static string XmlSchemaNamedItem {
            get {
                return ResourceManager.GetString("XmlSchemaNamedItem", resourceCulture);
            }
        }
    }
}