// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(System.ServiceModel.DnsEndpointIdentity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.MessageSecurityVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.SpnEndpointIdentity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.UpnEndpointIdentity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.X509CertificateEndpointIdentity))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.ISecurityCapabilities))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.LocalClientSecuritySettings))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.SecurityBindingElement))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.SecurityHeaderLayout))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.TransportSecurityBindingElement))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.SecurityKeyEntropyMode))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.BasicSecurityProfileVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.IdentityVerifier))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.SecureConversationVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.SecurityAlgorithmSuite))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.SecurityPolicyVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.SecurityVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.TrustVersion))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.BinarySecretSecurityToken))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.IssuedSecurityTokenParameters))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.SecureConversationSecurityTokenParameters))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.SecurityTokenParameters))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.ServiceModelSecurityTokenRequirement))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.SupportingTokenParameters))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Security.Tokens.UserNameSecurityTokenParameters))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Claims.ClaimSet))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Claims.Claim))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Policy.IAuthorizationPolicy))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Policy.IAuthorizationComponent))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Policy.AuthorizationContext))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Tokens.GenericXmlSecurityToken))]
[assembly: TypeForwardedTo(typeof(System.IdentityModel.Tokens.GenericXmlSecurityKeyIdentifierClause))]
