//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSGallery259915_SOAPEncoded_awsomo_afip_gov_wsdl_NS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10Sel" +
        "ectServiceImpl", ConfigurationName="VSGallery259915_SOAPEncoded_awsomo_afip_gov_wsdl_NS.ContribuyenteNivel10SelectSer" +
        "viceImpl")]
    public interface ContribuyenteNivel10SelectServiceImpl
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public interface ContribuyenteNivel10SelectServiceImplChannel : VSGallery259915_SOAPEncoded_awsomo_afip_gov_wsdl_NS.ContribuyenteNivel10SelectServiceImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "99.99.99")]
    public partial class ContribuyenteNivel10SelectServiceImplClient : System.ServiceModel.ClientBase<VSGallery259915_SOAPEncoded_awsomo_afip_gov_wsdl_NS.ContribuyenteNivel10SelectServiceImpl>, VSGallery259915_SOAPEncoded_awsomo_afip_gov_wsdl_NS.ContribuyenteNivel10SelectServiceImpl
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContribuyenteNivel10SelectServiceImplClient() : 
                base(ContribuyenteNivel10SelectServiceImplClient.GetDefaultBinding(), ContribuyenteNivel10SelectServiceImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.select_ContribuyenteNivel10SelectServiceImpl.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(EndpointConfiguration endpointConfiguration) : 
                base(ContribuyenteNivel10SelectServiceImplClient.GetBindingForEndpoint(endpointConfiguration), ContribuyenteNivel10SelectServiceImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContribuyenteNivel10SelectServiceImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContribuyenteNivel10SelectServiceImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.select_ContribuyenteNivel10SelectServiceImpl))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.select_ContribuyenteNivel10SelectServiceImpl))
            {
                return new System.ServiceModel.EndpointAddress("http://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10Sele" +
                        "ctServiceImpl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ContribuyenteNivel10SelectServiceImplClient.GetBindingForEndpoint(EndpointConfiguration.select_ContribuyenteNivel10SelectServiceImpl);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ContribuyenteNivel10SelectServiceImplClient.GetEndpointAddress(EndpointConfiguration.select_ContribuyenteNivel10SelectServiceImpl);
        }
        
        public enum EndpointConfiguration
        {
            
            select_ContribuyenteNivel10SelectServiceImpl,
        }
    }
}