FROM microsoft/dotnet:1.0-sdk

# Install .NET Core 2.0 SDK
ENV DOTNET_SDK_VERSION 2.1.200
ENV DOTNET_SDK_DOWNLOAD_URL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz

RUN curl -SL $DOTNET_SDK_DOWNLOAD_URL --output dotnet.tar.gz \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz

RUN echo "%HOSTIP $SERVICEID" >> /etc/hosts

RUN mkdir -p /app
WORKDIR /app
COPY . /app/
CMD ["dotnet","vstest","--logger:trx;LogFileName=../TestOutput/out.trx", "dotnet-svcutil.test.dll"]
